version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORTS}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SQL_DB_URI}
      SPRING_DATASOURCE_USERNAME: ${SQL_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SQL_DB_PWD}
      SPRING_DATA_MONGODB_URI: ${NOSQL_DB_URI}
    depends_on:
      - sqldb
      - nosqldb
    volumes:
      - ${APP_VOLUMES}
    env_file:
      - .env

  sqldb:
    image: ${SQL_DB_IMAGE}
    environment:
      POSTGRES_DB: ${SQL_DB_NAME}
      POSTGRES_USER: ${SQL_DB_USERNAME}
      POSTGRES_PASSWORD: ${SQL_DB_PWD}
    ports:
      - ${SQL_DB_PORTS}
    volumes:
      - ${SQL_DB_VOLUMES}
    env_file:
      - .env

  nosqldb:
    image: ${NOSQL_DB_IMAGE}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NOSQL_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${NOSQL_DB_PASSWORD}
    ports:
      - ${NOSQL_DB_PORTS}
    volumes:
      - ${NOSQL_DB_VOLUMES}
    env_file:
      - .env

volumes:
  sql_data:
    driver: local
  nosql_data:
    driver: local
